---
- hosts: prod
  tasks:
  - name: "Dependencias do S.O"
    apt: name={{item}} state=present
    with_items:
    - python
    - python-dev
    - python-pip
    - git

  - name: "Fazendo deploy da aplicacao"
    git:
      repo: https://github.com/AlissonMMenezes/hello-openshift.git
      dest: /opt/hello

  - name: "Instalando dependencias da aplicacao"
    shell: pip install -r /opt/hello/requirements.txt

  - name: "Executando a aplicacao"
    shell: "nohup python /opt/hello/app.py &"